id: eb5c978da87d464292f3233ad0a4cfa6
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_543-The_Root_Manual_of_the_Rites_of_Manjusri-v2
  language: en-us
  author: ''
  volume: {}
